# Generated by Django 2.0 on 2019-02-09 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ComSemApp', '0014_auto_20190121_1551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reply',
            name='message',
            field=models.CharField(max_length=1023),
        ),
    ]
